apiVersion: v1
kind: LimitRange
metadata:
  name: nicelimits
spec:
  limits:
  - type: Pod 
    max:
      cpu: 1000m
      memory: 1Gi 
  - type: Container
    min:
      cpu: 100m
      memory: 8Mi 

